name: NHMC
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.0
  - pytorch=1.7.0
  - torchvision=0.8.1
  - numpy=1.19.2
  - pip:
    - matplotlib==3.7.5
    - albumentations==0.4.3
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - taming-transformers==0.0.1
    - taming-transformers-rom1504==0.0.6
    - torch-fidelity==0.3.0
    - torchmetrics==0.5.0
    - transformers==4.3.1
    - diffusers==0.26.2
    - lpips==0.1.4
  